### ISSUE TITLE
Unable to load settings

### ISSUE THREAD

**Issue by tokejepsen** [FOGProject/fog-client#52]
I'm getting the same error as described here; https://forums.fogproject.org/topic/7317/unable-to-find-settings-json/2.

SmartInstaller v0.10.5
Windows 7

Sorry for posting here. Can't seem to register on the forums, as I'm not getting any confirmation email.

**Comment by mastacontrola** [comment]
What's your email address?  You can get me on hangouts.  tommygunsster@gmail.com.

Once I get your message I'll edit this comment.

The file issue, itself, is non-problematic.  It creates the file and logs the error on completely fresh installations because the file simply doesn't exist.  That error, by itself, is nothing.

**Comment by tokejepsen** [comment]
The installation doesn't complete, with the same error message "Unable to install CA Certificate". Checking the zazzles log shows the "Unable to load settings".
